// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opcjifbdwpyttaxqlqbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wY2ppZmJkd3B5dHRheHFscWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDE2NzksImV4cCI6MjA3MDgxNzY3OX0.Tv-51_TU_NBbQRQOAxFLRu_GKb435CiwV3kEg1Puj3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});